### ISSUE TITLE
How to get a screenshot at time?

### ISSUE THREAD

**Issue by phamvankhang** [hansalemaos/adbnativeblitz#1]

**Comment by hansalemaos** [comment]
Do you mean a one time only screenshot?

**Comment by phamvankhang** [comment]
> Do you mean a one time only screenshot?

yes, i have an issue about delay time when a take a screenshot. when i use your lib, i have an idea about keep it run in a thread and i will take last screenshot from it

**Comment by hansalemaos** [comment]
If you want to take only one screenshot, let's say every 5 minutes, it doesn't make sense to use this library neither scrcpy 

**From scrcpy** 
> low startup time: ~1 second to display the first image

Since both use video codecs, there is always a delay at the beginning, but after the initial delay, it is really fast.

What you can do is keep it running in the background and grab the screenshots when you need them;
